<?xml version="1.0" encoding="utf-8"?><Database Name="Bolnica" Class="BolnicaBazaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TMSUCE8\SQLEXPRESS;Initial Catalog=Bolnica;Integrated Security=True" SettingsObjectName="BolnicaVezba.Properties.Settings" SettingsPropertyName="BolnicaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pacijent" Member="Pacijents">
    <Type Name="Pacijent">
      <Column Name="IDPacijent" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prioritet" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrDana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OdeljenjeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SobaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Soba_Pacijent" Member="Soba" ThisKey="SobaID" OtherKey="SobaID" Type="Soba" IsForeignKey="true" />
      <Association Name="Odeljenje_Pacijent" Member="Odeljenje" ThisKey="OdeljenjeID" OtherKey="OdeljenjeID" Type="Odeljenje" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Soba" Member="Sobas">
    <Type Name="Soba">
      <Column Name="SobaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OdeljenjeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sprat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Soba_Pacijent" Member="Pacijents" ThisKey="SobaID" OtherKey="SobaID" Type="Pacijent" />
      <Association Name="Odeljenje_Soba" Member="Odeljenje" ThisKey="OdeljenjeID" OtherKey="OdeljenjeID" Type="Odeljenje" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Odeljenje" Member="Odeljenjes">
    <Type Name="Odeljenje">
      <Column Name="OdeljenjeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Odeljenje_Pacijent" Member="Pacijents" ThisKey="OdeljenjeID" OtherKey="OdeljenjeID" Type="Pacijent" />
      <Association Name="Odeljenje_Soba" Member="Sobas" ThisKey="OdeljenjeID" OtherKey="OdeljenjeID" Type="Soba" />
    </Type>
  </Table>
</Database>